[package]
name = "smolres"
authors = ["Max Hammer"]
description = "A CLI tool to pixelate images into low-res blocks."
version = "10.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
jpeg-decoder = "0.3.1"
jpeg-encoder = "0.6.1"
thiserror = "2.0.12"
